name: Build STM32F4 Project

# Trigger the workflow on push or pull request to the main branch
on:
    push:
      branches:
        - main
      paths:
        - '**/*.c'
        - '**/*.h'
    pull_request:
      branches:
        - main
      paths:
        - '**/*.c'
        - '**/*.h'  

jobs:
  build:
    runs-on: ubuntu-latest  # You can change this to any supported runner

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up ARM toolchain
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc-arm-none-eabi make

    - name: Build STM32 project
      run: |
        make  # or replace with cmake if your project uses CMake

    - name: Check build artifacts
      if: success()
      run: echo "Build successful!"

    - name: Check build artifacts
      run: |
        if [ -f build/binaries/firmware.elf ]; then
            echo "Build successful!"
        else
            echo "Build failed!" && exit 1
        fi
